# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anasayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(893, 611)
        
        # Modern dark theme styling
        dark_style = """
            QWidget {
                background-color: #2b2b2b;
                color: #ffffff;
                font-family: 'Segoe UI', Arial;
            }
            
            QLineEdit, QComboBox, QDateEdit, QSpinBox {
                background-color: #3b3b3b;
                border: 1px solid #555555;
                border-radius: 4px;
                padding: 4px;
                color: #ffffff;
                selection-background-color: #4a4a4a;
            }
            
            QLineEdit:focus, QComboBox:focus, QDateEdit:focus {
                border: 1px solid #5c88c5;
            }
            
            QPushButton {
                background-color: #3d5a80;
                color: white;
                border: none;
                border-radius: 4px;
                padding: 6px 12px;
                font-weight: bold;
            }
            
            QPushButton:hover {
                background-color: #4a6b95;
            }
            
            QPushButton:pressed {
                background-color: #345070;
            }
            
            QTableWidget {
                background-color: #2b2b2b;
                alternate-background-color: #323232;
                border: 1px solid #3b3b3b;
                gridline-color: #3b3b3b;
                color: #ffffff;
                selection-background-color: #3d5a80;
            }
            
            QTableWidget::item {
                padding: 4px;
            }
            
            QHeaderView::section {
                background-color: #3b3b3b;
                color: #ffffff;
                padding: 6px;
                border: none;
                font-weight: bold;
            }
            
            QScrollBar:vertical {
                border: none;
                background-color: #2b2b2b;
                width: 10px;
                margin: 0px;
            }
            
            QScrollBar::handle:vertical {
                background-color: #5c88c5;
                border-radius: 5px;
                min-height: 20px;
            }
            
            QScrollBar::handle:vertical:hover {
                background-color: #6b99d8;
            }
            
            QLabel {
                color: #ffffff;
            }
            
            QMessageBox {
                background-color: #2b2b2b;
                color: #ffffff;
            }
            
            QMessageBox QPushButton {
                min-width: 70px;
                min-height: 25px;
            }
            
            #btnAIAnalysis {
                background-color: #6a329f;
            }
            
            #btnAIAnalysis:hover {
                background-color: #7b42b0;
            }
            
            #btnAIAnalysis:pressed {
                background-color: #592689;
            }
        """
        
        Form.setStyleSheet(dark_style)
        
        self.tblYeni = QtWidgets.QTableWidget(Form)
        self.tblYeni.setGeometry(QtCore.QRect(10, 280, 641, 311))
        self.tblYeni.setRowCount(31)
        self.tblYeni.setColumnCount(6)
        self.tblYeni.setObjectName("tblYeni")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 135, 33))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.kayitTarih = QtWidgets.QCalendarWidget(Form)
        self.kayitTarih.setGeometry(QtCore.QRect(10, 50, 312, 183))
        self.kayitTarih.setObjectName("kayitTarih")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(610, 20, 271, 251))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lneMarket = QtWidgets.QLineEdit(self.groupBox)
        self.lneMarket.setGeometry(QtCore.QRect(100, 20, 161, 41))
        self.lneMarket.setObjectName("lneMarket")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lneAciklama = QtWidgets.QLineEdit(self.groupBox)
        self.lneAciklama.setGeometry(QtCore.QRect(90, 170, 171, 71))
        self.lneAciklama.setObjectName("lneAciklama")
        self.lneFatura = QtWidgets.QLineEdit(self.groupBox)
        self.lneFatura.setGeometry(QtCore.QRect(100, 70, 161, 41))
        self.lneFatura.setObjectName("lneFatura")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lneHarcama = QtWidgets.QLineEdit(self.groupBox)
        self.lneHarcama.setGeometry(QtCore.QRect(100, 120, 161, 41))
        self.lneHarcama.setObjectName("lneHarcama")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 210, 71, 31))
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("color: rgb(255, 0, 0)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.chkToplam = QtWidgets.QCheckBox(Form)
        self.chkToplam.setGeometry(QtCore.QRect(100, 250, 91, 17))
        self.chkToplam.setChecked(False)
        self.chkToplam.setObjectName("chkToplam")
        self.chkButunKayitlar = QtWidgets.QCheckBox(Form)
        self.chkButunKayitlar.setGeometry(QtCore.QRect(10, 250, 91, 17))
        self.chkButunKayitlar.setChecked(False)
        self.chkButunKayitlar.setObjectName("chkButunKayitlar")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(330, 20, 271, 251))
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 100, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lneGelirAciklama = QtWidgets.QLineEdit(self.groupBox_2)
        self.lneGelirAciklama.setGeometry(QtCore.QRect(90, 170, 171, 71))
        self.lneGelirAciklama.setObjectName("lneGelirAciklama")
        self.lneGelirMiktar = QtWidgets.QLineEdit(self.groupBox_2)
        self.lneGelirMiktar.setGeometry(QtCore.QRect(100, 100, 161, 41))
        self.lneGelirMiktar.setObjectName("lneGelirMiktar")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 170, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.btnGelirKayit = QtWidgets.QPushButton(self.groupBox_2)
        self.btnGelirKayit.setGeometry(QtCore.QRect(10, 210, 71, 31))
        self.btnGelirKayit.setAutoFillBackground(False)
        self.btnGelirKayit.setStyleSheet("color: rgb(0, 170, 0);")
        self.btnGelirKayit.setObjectName("btnGelirKayit")
        self.cmbKaynak = QtWidgets.QComboBox(self.groupBox_2)
        self.cmbKaynak.setGeometry(QtCore.QRect(100, 30, 161, 41))
        self.cmbKaynak.setObjectName("cmbKaynak")
        self.cmbKaynak.addItem("")
        self.cmbKaynak.addItem("")
        self.cmbKaynak.addItem("")
        self.cmbKaynak.addItem("")
        self.cmbKaynak.addItem("")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(670, 280, 151, 236))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnGelirListe = QtWidgets.QPushButton(self.layoutWidget)
        self.btnGelirListe.setAutoFillBackground(False)
        self.btnGelirListe.setStyleSheet("color: rgb(0, 170, 0);")
        self.btnGelirListe.setObjectName("btnGelirListe")
        self.verticalLayout.addWidget(self.btnGelirListe)
        self.btnListele = QtWidgets.QPushButton(self.layoutWidget)
        self.btnListele.setAutoFillBackground(False)
        self.btnListele.setStyleSheet("color:rgb(191, 0, 0)")
        self.btnListele.setObjectName("btnListele")
        self.verticalLayout.addWidget(self.btnListele)
        self.btnNot = QtWidgets.QPushButton(self.layoutWidget)
        self.btnNot.setStyleSheet("color:rgb(255, 170, 0)")
        self.btnNot.setObjectName("btnNot")
        self.verticalLayout.addWidget(self.btnNot)
        self.btnSil = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue,sans-serif")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.btnSil.setFont(font)
        self.btnSil.setObjectName("btnSil")
        self.verticalLayout.addWidget(self.btnSil)
        self.btnGuncelle = QtWidgets.QPushButton(self.layoutWidget)
        self.btnGuncelle.setObjectName("btnGuncelle")
        self.verticalLayout.addWidget(self.btnGuncelle)
        self.btnHesaplarGiris = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue,sans-serif")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.btnHesaplarGiris.setFont(font)
        self.btnHesaplarGiris.setAutoFillBackground(False)
        self.btnHesaplarGiris.setStyleSheet("color:rgb(250, 80, 255)")
        self.btnHesaplarGiris.setObjectName("btnHesaplarGiris")
        self.verticalLayout.addWidget(self.btnHesaplarGiris)

        # Add AI Analysis Button
        self.btnAIAnalysis = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue,sans-serif")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.btnAIAnalysis.setFont(font)
        self.btnAIAnalysis.setObjectName("btnAIAnalysis")
        self.btnAIAnalysis.setStyleSheet("color: rgb(75, 0, 130);")  # Purple color for AI button
        self.verticalLayout.addWidget(self.btnAIAnalysis)

        # Buton boyutlarını ayarla
        min_width = 85
        min_height = 30
        
        self.btnGelirListe.setMinimumSize(min_width, min_height)
        self.btnListele.setMinimumSize(min_width, min_height)
        self.btnNot.setMinimumSize(min_width, min_height)
        self.btnSil.setMinimumSize(min_width, min_height)
        self.btnGuncelle.setMinimumSize(min_width, min_height)
        self.btnHesaplarGiris.setMinimumSize(min_width, min_height)
        self.btnAIAnalysis.setMinimumSize(min_width, min_height)

        self.retranslateUi(Form)
        self.cmbKaynak.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "BÜTÇE RAPOR PROGRAMI - O.O.A | 2024"))
        self.label.setText(_translate("Form", "KAYIT TARİH:"))
        self.groupBox.setTitle(_translate("Form", "GİDERLER :"))
        self.label_2.setText(_translate("Form", "MARKET:"))
        self.label_3.setText(_translate("Form", "FATURA:"))
        self.label_4.setText(_translate("Form", "DİĞER:"))
        self.label_5.setText(_translate("Form", "AÇIKLAMA:"))
        self.pushButton_2.setText(_translate("Form", "EKLE"))
        self.chkToplam.setText(_translate("Form", "ToplamListele"))
        self.chkButunKayitlar.setText(_translate("Form", "Bütün Kayıtlar"))
        self.groupBox_2.setTitle(_translate("Form", "GELİRLER :"))
        self.label_6.setText(_translate("Form", "KAYNAK : "))
        self.label_7.setText(_translate("Form", "MİKTAR : "))
        self.label_9.setText(_translate("Form", "AÇIKLAMA:"))
        self.btnGelirKayit.setText(_translate("Form", "KAYIT"))
        self.cmbKaynak.setItemText(0, _translate("Form", "Serbest Çalışma"))
        self.cmbKaynak.setItemText(1, _translate("Form", "Kira Geliri"))
        self.cmbKaynak.setItemText(2, _translate("Form", "Maaş"))
        self.cmbKaynak.setItemText(3, _translate("Form", "Yatırım Getirisi"))
        self.cmbKaynak.setItemText(4, _translate("Form", "Diğer"))
        self.btnGelirListe.setText(_translate("Form", "GELİR GÖRÜNTÜLE"))
        self.btnListele.setText(_translate("Form", "GİDER GÖRÜNTÜLE"))
        self.btnNot.setText(_translate("Form", "HIZLI NOTLAR"))
        self.btnSil.setText(_translate("Form", "KAYIT SİL"))
        self.btnGuncelle.setText(_translate("Form", "GÜNCELLE"))
        self.btnHesaplarGiris.setText(_translate("Form", "DİJİTAL HESAPLAR"))
        self.btnAIAnalysis.setText(_translate("Form", "AI ANALİZ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
